name: Weekly Text Message

on:
  schedule:
    # Run every morning at 9 am est
    - cron: "0 13 * * 1"

jobs:
  send_text:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel API to Send Text
        run: |
          response=$(curl -s -w "\nHTTP_CODE:%{http_code}\n" -X POST https://foxs-inventory-levels.vercel.app/api/send-text)
          echo "$response"
        shell: bash
